// Keys generated by http://travistidwell.com/jsencrypt/demo/
const jwt = require('jsonwebtoken');
const fs = require('fs');

console.log('Initialisation');

const payload = {
    "login": "user",
    "password": "123456",
    "iat": Math.floor(Date.now() / 1000) - 30
  },
  secret = "Secret_Passw0rd",
  private_key = fs.readFileSync('private.key'),
  public_key = fs.readFileSync('public.key');

console.log("Sign with password...");
var token = jwt.sign(payload, secret, {
  expiresIn: 60 * 60  // 1 hour expiration
});

console.log(token);
jwt.verify(token, secret, function(err, decoded) {
  console.log("Decoded login :" + decoded.login);
});

//
console.log('Sign with private key ...');
token = jwt.sign(payload, private_key, {
  algorithm: 'RS256'
});
console.log(token);
jwt.verify(token, public_key, function(err, decoded) {
  console.log("Decoded login :" + decoded.login);
});
